## 1. Creating NumPy Arrays

In [4]:
list_1 = [1,2,3]
print(list_1)

[1, 2, 3]


In [6]:
import numpy as np

In [10]:
numpy_1 = np.array(list_1) #converts list in np array
print(numpy_1)

[1 2 3]


In [12]:
#we can create zeroes or ones arrays
zeroes_array = np.zeros(5)
print(zeroes_array)

[0. 0. 0. 0. 0.]


In [14]:
ones_array = np.ones(10)
print(ones_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [24]:
#We can also set a range of values
range_array_1 = np.arange(5)  #until 5th element
print(range_array_1)

[0 1 2 3 4]


In [28]:
range_array_2 = np.arange(5,11)  #from 5th until 10th element
print(range_array_2)

[ 5  6  7  8  9 10]


In [34]:
range_array_3 = np.arange(0,20,2)  #from 1st until 20th element in steps of 2
print(range_array_3)

[ 0  2  4  6  8 10 12 14 16 18]


In [44]:
linspace_array = np.linspace(0,10,5)  #linspace generates an array from first parameter to second parameter, inclusive
print(linspace_array)

[ 0.   2.5  5.   7.5 10. ]


## 2. Fetch Operations

In [52]:
an_array = np.arange(0,11)
print(an_array)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [58]:
an_array[0] #call by index of array

0

In [60]:
first_five = an_array[:5]
print(first_five)

[0 1 2 3 4]


In [68]:
first_five_reversed = an_array[4::-1] #from, until, in this order (if 1 there, prints an empty array
print(first_five_reversed)

[4 3 2 1 0]


In [74]:
final_two = an_array[-2:] #from the one before last, until it finishes
print(final_two)

[ 9 10]


In [78]:
#properties of an array
print(an_array.size) #number of elements

11


In [80]:
np.amax(an_array) #max_value
#np.amin() #min_value
#np.average() #min_value

print(np.amax(an_array))

10


## Matrix Fetch operations

In [1]:
import numpy as np

In [2]:
a_matrix = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(a_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print(a_matrix[0]) #returns an array of an array

[[1 2 3]]


In [5]:
#now, if we want a single element, like the number 4 inside the matrix
print(a_matrix[1,0]) #second row, first element

4


In [8]:
#now if we want multiple elements
print(a_matrix[2,1:3])

[[8 9]]


In [16]:
#Matrix specific properties
print(a_matrix.size) #Total number of individual elements
print(a_matrix.shape) #rows, columns

9
(3, 3)


In [19]:
print(np.amax(a_matrix)) #returns the max value
print(np.amin(a_matrix)) #returns the min value
print(np.average(a_matrix)) #returns the average

9
1
5.0


In [22]:
#other way of having the same results
print(a_matrix.max())
print(a_matrix.min())
print(a_matrix.mean())

9
1
5.0


## Numpy modification functions

In [24]:
import numpy as np

In [26]:
a_matrix = np.matrix([[1,2],[3,4]])
print(a_matrix)

[[1 2]
 [3 4]]


In [28]:
a_matrix[1,0] = 10 #second vector, row zero
print(a_matrix)

[[ 1  2]
 [10  4]]


In [30]:
a_matrix[0] = [6,3] #change entire first row
print(a_matrix)

[[ 6  3]
 [10  4]]


In [31]:
print(np.sort(a_matrix)) #sort ascending

[[ 3  6]
 [ 4 10]]


In [32]:
print(-np.sort(-a_matrix)) #sort descending

[[ 6  3]
 [10  4]]


In [33]:
#transpose
a_matrix = np.matrix([[1,2],[3,4]])
print(a_matrix.T)

[[1 3]
 [2 4]]


In [34]:
print(a_matrix.flatten())

[[1 2 3 4]]


In [36]:
print(a_matrix *2)

[[2 4]
 [6 8]]


In [37]:
#numpy add function
print(np.add(a_matrix, a_matrix))

[[2 4]
 [6 8]]


In [38]:
#matrix multiplication
print(np.matmul(a_matrix,a_matrix))

[[ 7 10]
 [15 22]]
