In [2]:
import numpy as np

In [4]:
student_grades = np.array([56,78,98,90,58,64,67,72,93,51])
print(student_grades)

[56 78 98 90 58 64 67 72 93 51]


In [8]:
class_average = np.average(student_grades)
print(class_average)

72.7


In [12]:
highest_grade = np.amax(student_grades)
print(highest_grade)

98


In [14]:
lowest_grade = np.amin(student_grades)
print(lowest_grade)

51


In [18]:
#to find the index of max or min
print(np.argmax(student_grades))
print(np.argmin(student_grades))

2
9


In [20]:
#sort in ascending or descending
print(np.sort(student_grades))

[51 56 58 64 67 72 78 90 93 98]


In [22]:
print(-np.sort(-student_grades))

[98 93 90 78 72 67 64 58 56 51]


In [24]:
#increase every grade
increased_grades = student_grades *1.1
print(increased_grades)

[ 61.6  85.8 107.8  99.   63.8  70.4  73.7  79.2 102.3  56.1]


In [28]:
print(np.add(student_grades, np.ones(10)))

[57. 79. 99. 91. 59. 65. 68. 73. 94. 52.]
